spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10  # 允许最大连接数，默认8（负值表示没有限制）
        max-idle: 8     # 最大空闲连接数，默认8
        min-idle: 0     # 最小空闲连接数，默认0
        max-wait: 5s    # 连接用完时，新的请求等待时间(s秒、ms毫秒)，超过该时间抛出异常JedisConnectionException，(默认-1，负值表示没有限制)
        time-between-eviction-runs: 1s # 空闲线程
